In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent = ['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am a good boy', 'I am a good developer', 'understand the meaning of words', 'your videos are good']

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size = 10000

In [6]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
print(one_hot_repr)

[[6481, 9339, 4113, 7538], [6481, 9339, 4113, 3308], [6481, 2452, 4113, 4045], [8146, 1967, 1781, 9102, 7951], [8146, 1967, 1781, 9102, 7064], [4279, 6481, 7281, 4113, 6096], [6858, 4622, 5097, 9102]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding = 'pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6481 9339 4113 7538]
 [   0    0    0    0 6481 9339 4113 3308]
 [   0    0    0    0 6481 2452 4113 4045]
 [   0    0    0 8146 1967 1781 9102 7951]
 [   0    0    0 8146 1967 1781 9102 7064]
 [   0    0    0 4279 6481 7281 4113 6096]
 [   0    0    0    0 6858 4622 5097 9102]]


In [10]:
dim = 15

In [17]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [18]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 15)             150000    
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
print(model.predict(embedded_docs))

[[[ 0.0367424   0.01587402 -0.01222236  0.02779979 -0.04243096
    0.03883299 -0.02918472  0.00489838  0.02899534  0.04358286
    0.02914668  0.04553726 -0.00778642 -0.03882313 -0.01723869]
  [ 0.0367424   0.01587402 -0.01222236  0.02779979 -0.04243096
    0.03883299 -0.02918472  0.00489838  0.02899534  0.04358286
    0.02914668  0.04553726 -0.00778642 -0.03882313 -0.01723869]
  [ 0.0367424   0.01587402 -0.01222236  0.02779979 -0.04243096
    0.03883299 -0.02918472  0.00489838  0.02899534  0.04358286
    0.02914668  0.04553726 -0.00778642 -0.03882313 -0.01723869]
  [ 0.0367424   0.01587402 -0.01222236  0.02779979 -0.04243096
    0.03883299 -0.02918472  0.00489838  0.02899534  0.04358286
    0.02914668  0.04553726 -0.00778642 -0.03882313 -0.01723869]
  [-0.01548351 -0.03010699  0.006442   -0.04685405 -0.04895775
   -0.03034351 -0.0353173   0.00986425  0.02339439 -0.00886775
   -0.02930436  0.01780612 -0.03213765 -0.00865065  0.00560743]
  [ 0.04565351 -0.03040881 -0.00658219  0.00935094

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 6481, 9339, 4113, 7538], dtype=int32)

In [21]:
print(model.predict(embedded_docs[0]))

[[[ 0.0367424   0.01587402 -0.01222236  0.02779979 -0.04243096
    0.03883299 -0.02918472  0.00489838  0.02899534  0.04358286
    0.02914668  0.04553726 -0.00778642 -0.03882313 -0.01723869]]

 [[ 0.0367424   0.01587402 -0.01222236  0.02779979 -0.04243096
    0.03883299 -0.02918472  0.00489838  0.02899534  0.04358286
    0.02914668  0.04553726 -0.00778642 -0.03882313 -0.01723869]]

 [[ 0.0367424   0.01587402 -0.01222236  0.02779979 -0.04243096
    0.03883299 -0.02918472  0.00489838  0.02899534  0.04358286
    0.02914668  0.04553726 -0.00778642 -0.03882313 -0.01723869]]

 [[ 0.0367424   0.01587402 -0.01222236  0.02779979 -0.04243096
    0.03883299 -0.02918472  0.00489838  0.02899534  0.04358286
    0.02914668  0.04553726 -0.00778642 -0.03882313 -0.01723869]]

 [[-0.01548351 -0.03010699  0.006442   -0.04685405 -0.04895775
   -0.03034351 -0.0353173   0.00986425  0.02339439 -0.00886775
   -0.02930436  0.01780612 -0.03213765 -0.00865065  0.00560743]]

 [[ 0.04565351 -0.03040881 -0.00658219  